# Generated by Django 5.0.3 on 2024-03-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='teachers/')),
                ('speciality', models.CharField(max_length=150)),
                ('telegram_link', models.CharField(max_length=250)),
                ('instagram_link', models.CharField(max_length=250)),
                ('linkedin_link', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
