# Generated by Django 5.0.3 on 2024-03-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=250, null=True)),
                ('course_count', models.PositiveIntegerField(default=1)),
                ('image', models.ImageField(upload_to='course/category_pictures/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250, null=True)),
                ('student_count', models.PositiveIntegerField(default=1)),
                ('duration', models.PositiveIntegerField(default=1)),
                ('price', models.PositiveIntegerField()),
                ('rating', models.IntegerField()),
                ('image', models.ImageField(upload_to='course/course_pictures/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
