# Generated by Django 5.0.3 on 2024-03-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('p', 'Publish'), ('d', 'Draft')], default='p', max_length=5),
        ),
    ]
